name: CI – Cypress

on:
  push:
    branches: [ "feat/config-tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (incluye devDependencies)
        run: npm ci
        env:
          NODE_ENV: ""   # evita que npm omita devDependencies

      - name: Mostrar dónde quedó Cypress
        run: node -p "require.resolve('cypress/package.json')"

      - name: Verificar Cypress
        run: npx cypress verify

      - name: Run Cypress E2E
        env:
          BASE_URL: https://example.cypress.io
        run: npx cypress run --spec cypress/e2e/sanity.cy.js
