name: CI - Cypress

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Verificar instalación de Cypress
        run: npx cypress verify

      - name: Ejecutar pruebas E2E con configuración explícita
        run: npx cypress run --config-file cypress.config.js --spec cypress/e2e/sanity.cy.js

      - name: Subir artefactos (si falla)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/**
            cypress/screenshots/**
